apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "konnectivity-server.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "konnectivity-server.labels" . | nindent 4 }}
    kubernetes.io/cluster-service: "true"
