{{- if .Values.server.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: konnectivity-server
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "konnectivity-server.labels" . | indent 4 }}
{{- if .Values.server.serviceMonitor.extraLabels }}
{{ toYaml .Values.server.serviceMonitor.extraLabels | indent 4 }}
{{- end }}
spec:
  jobLabel: jobLabel
  selector:
    matchLabels:
{{ include "konnectivity-server.selectorLabels" . | indent 6}}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
  - port: http-metrics
    path: /metrics
    {{- if .Values.server.serviceMonitor.interval}}
    interval: {{ .Values.server.serviceMonitor.interval }}
    {{- end }}
    {{- if .Values.server.serviceMonitor.proxyUrl }}
    proxyUrl: {{ .Values.server.serviceMonitor.proxyUrl}}
    {{- end }}
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
{{- if .Values.server.serviceMonitor.metricRelabelings }}
    metricRelabelings:
{{ tpl (toYaml .Values.server.serviceMonitor.metricRelabelings | indent 4) . }}
{{- end }}
{{- if .Values.server.serviceMonitor.relabelings }}
    relabelings:
{{ tpl (toYaml .Values.server.serviceMonitor.relabelings | indent 4) . }}
{{- end }}
{{- end }}
