apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "konnectivity-agent.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "konnectivity-agent.labels" . | nindent 4 }}
    kubernetes.io/cluster-service: "true"
